package agilelens.understudy.teleprompter

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.descriptors.buildClassSerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.JsonDecoder
import kotlinx.serialization.json.JsonEncoder
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

/**
 * Structured play script — Acts → Scenes → Entries. Kotlin mirror of Swift's
 * PlayScript. Loaded from asset JSONs generated by scripts/parse_hamlet.py
 * (Shakespeare format) and scripts/parse_modern.py (Chekhov/Wilde format).
 *
 * Same 5 plays bundled as iOS + visionOS:
 *   Hamlet (Shakespeare, Gutenberg #1524)
 *   Macbeth (Shakespeare, Gutenberg #1533)
 *   A Midsummer Night's Dream (Shakespeare, Gutenberg #1514)
 *   The Seagull (Chekhov, Gutenberg #1754)
 *   The Importance of Being Earnest (Wilde, Gutenberg #844)
 */
@Serializable
data class PlayScript(
    val title: String,
    val author: String,
    val source: String = "",
    val acts: List<Act>,
) {
    @Serializable
    data class Act(
        val number: Int,
        val roman: String,
        val scenes: List<Scene>,
    )

    @Serializable
    data class Scene(
        val number: Int,
        val roman: String,
        val location: String,
        val entries: List<Entry>,
    )

    /**
     * An entry in a scene — either a spoken line with character + lineID
     * ("1.1.1", "Act.Scene.LineNumber"), or a stage direction. Custom
     * serializer matches the JSON shape: {"kind": "line"|"stage", …}.
     */
    @Serializable(with = EntrySerializer::class)
    sealed class Entry {
        abstract val text: String

        data class Line(
            val character: String,
            override val text: String,
            val lineID: String,
        ) : Entry()

        data class Stage(
            override val text: String,
        ) : Entry()
    }

    /** Flat list of line entries across the whole play, in reading order. */
    data class LocatedLine(
        val actRoman: String,
        val sceneRoman: String,
        val location: String,
        val character: String,
        val text: String,
        val lineID: String,
    )

    val allLines: List<LocatedLine>
        get() = buildList {
            for (act in acts) {
                for (scene in act.scenes) {
                    for (entry in scene.entries) {
                        if (entry is Entry.Line) {
                            add(LocatedLine(
                                actRoman = act.roman,
                                sceneRoman = scene.roman,
                                location = scene.location,
                                character = entry.character,
                                text = entry.text,
                                lineID = entry.lineID,
                            ))
                        }
                    }
                }
            }
        }

    /** Case-insensitive filter over character + line text. */
    fun linesMatching(query: String): List<LocatedLine> {
        val trimmed = query.trim()
        if (trimmed.isEmpty()) return allLines
        val needle = trimmed.lowercase()
        return allLines.filter {
            it.text.lowercase().contains(needle) ||
                it.character.lowercase().contains(needle)
        }
    }
}

object EntrySerializer : KSerializer<PlayScript.Entry> {
    override val descriptor: SerialDescriptor = buildClassSerialDescriptor("Entry")

    override fun serialize(encoder: Encoder, value: PlayScript.Entry) {
        require(encoder is JsonEncoder) { "EntrySerializer requires JSON" }
        val obj = buildJsonObject {
            when (value) {
                is PlayScript.Entry.Line -> {
                    put("kind", JsonPrimitive("line"))
                    put("character", JsonPrimitive(value.character))
                    put("text", JsonPrimitive(value.text))
                    put("lineID", JsonPrimitive(value.lineID))
                }
                is PlayScript.Entry.Stage -> {
                    put("kind", JsonPrimitive("stage"))
                    put("text", JsonPrimitive(value.text))
                }
            }
        }
        encoder.encodeJsonElement(obj)
    }

    override fun deserialize(decoder: Decoder): PlayScript.Entry {
        require(decoder is JsonDecoder) { "EntrySerializer requires JSON" }
        val obj = decoder.decodeJsonElement().jsonObject
        val kind = obj.getValue("kind").jsonPrimitive.content
        return when (kind) {
            "line" -> PlayScript.Entry.Line(
                character = obj.getValue("character").jsonPrimitive.content,
                text = obj.getValue("text").jsonPrimitive.content,
                lineID = obj.getValue("lineID").jsonPrimitive.content,
            )
            "stage" -> PlayScript.Entry.Stage(
                text = obj.getValue("text").jsonPrimitive.content,
            )
            else -> throw IllegalArgumentException("Unknown Entry kind: $kind")
        }
    }
}
