#!/usr/bin/env bash
#
# ship-playstore.sh — build a signed .aab and upload to Google Play's
# Internal Testing track via the Google Play Developer API.
#
# Mirrors scripts/ship-testflight.sh for iOS. No fastlane, no Gradle
# plugins — just gradle + curl. The service account JSON is the Play
# analogue to ASC's .p8 key.
#
# Prereqs (one-time, see HANDOFF_GOOGLE_PLAY.md):
#   1. $25 Play Console account created + Understudy app registered.
#   2. Release keystore exists. Generated by bootstrap-asc-profile.sh
#      analogue — for Android we just ran:
#        keytool -genkeypair -keystore ~/.private_keys/understudy-release.jks
#                -alias understudy -validity 36500 ...
#      Password stored in ~/.private_keys/understudy-release.password.
#   3. Google Cloud service account JSON key with Play Developer API
#      access, linked in Play Console → Settings → Developer API.
#      Save at ~/.private_keys/understudy-playstore-publisher.json.
#
# Env vars the script reads:
#   PLAY_SERVICE_ACCOUNT_JSON   path to the service-account JSON (required)
#   UNDERSTUDY_KEYSTORE_PATH    path to the .jks (default ~/.private_keys/understudy-release.jks)
#   UNDERSTUDY_KEYSTORE_PASSWORD  keystore + key password (default: read from sibling .password file)
#   UNDERSTUDY_KEY_ALIAS        default "understudy"
#   PLAY_TRACK                  default "internal" ("alpha" / "beta" / "production")
#
# Exit codes:
#   0 success; 1 bad usage; 2 prereq missing; 3 build failed; 4 upload failed

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PACKAGE_NAME="agilelens.understudy"
TRACK="${PLAY_TRACK:-internal}"
KEYSTORE="${UNDERSTUDY_KEYSTORE_PATH:-$HOME/.private_keys/understudy-release.jks}"
KEY_ALIAS="${UNDERSTUDY_KEY_ALIAS:-understudy}"
PASSFILE="$(dirname "$KEYSTORE")/$(basename "${KEYSTORE%.*}").password"
: "${UNDERSTUDY_KEYSTORE_PASSWORD:=$(cat "$PASSFILE" 2>/dev/null || true)}"

# ─── Preflight ────────────────────────────────────────────────────────────
for v in PLAY_SERVICE_ACCOUNT_JSON UNDERSTUDY_KEYSTORE_PASSWORD; do
  if [[ -z "${!v:-}" ]]; then
    echo "✗ Missing \$$v. See HANDOFF_GOOGLE_PLAY.md for setup." >&2; exit 2
  fi
done
[[ -f "$PLAY_SERVICE_ACCOUNT_JSON" ]] || { echo "✗ Not found: $PLAY_SERVICE_ACCOUNT_JSON" >&2; exit 2; }
[[ -f "$KEYSTORE" ]] || { echo "✗ Keystore missing: $KEYSTORE" >&2; exit 2; }

AUTH_HELPER="$REPO_ROOT/../dev-control-center/scripts/play-auth.sh"
[[ -f "$AUTH_HELPER" ]] || { echo "✗ Fleet helper missing: $AUTH_HELPER (clone dev-control-center alongside this repo)" >&2; exit 2; }
# shellcheck disable=SC1090
source "$AUTH_HELPER"

# Ensure JDK17 + Android SDK picked up via Gradle wrapper. We pin to the
# Android Studio Preview bundled JBR since this machine has no Java 17
# on PATH by default.
ASP_JBR="/Applications/Android Studio Preview.app/Contents/jbr/Contents/Home"
if [[ -d "$ASP_JBR" ]]; then
  export JAVA_HOME="$ASP_JBR"
  export PATH="$JAVA_HOME/bin:$PATH"
fi

echo "┌─ Understudy → Google Play ──────────────────────────────────────"
echo "│  package  : $PACKAGE_NAME"
echo "│  track    : $TRACK"
echo "│  keystore : $KEYSTORE"
echo "└─────────────────────────────────────────────────────────────────"

# ─── 1. Build signed .aab ─────────────────────────────────────────────────
echo
echo "▶ gradle :app:bundleRelease"
export UNDERSTUDY_KEYSTORE_PATH="$KEYSTORE"
export UNDERSTUDY_KEYSTORE_PASSWORD
export UNDERSTUDY_KEY_ALIAS="$KEY_ALIAS"
cd "$REPO_ROOT/android"
./gradlew :app:bundleRelease || { echo "✗ bundleRelease failed" >&2; exit 3; }

AAB="$REPO_ROOT/android/app/build/outputs/bundle/release/app-release.aab"
[[ -f "$AAB" ]] || { echo "✗ .aab not produced at $AAB" >&2; exit 3; }
VERSION_CODE=$(grep -m1 'versionCode = ' "$REPO_ROOT/android/app/build.gradle.kts" | grep -oE '[0-9]+')
VERSION_NAME=$(grep -m1 'versionName = ' "$REPO_ROOT/android/app/build.gradle.kts" | sed -E 's/.*"([^"]+)".*/\1/')
echo "  built: $AAB  ($(du -h "$AAB" | cut -f1))"
echo "  version: $VERSION_NAME ($VERSION_CODE)"

# ─── 2. Start a Play edit ─────────────────────────────────────────────────
echo
echo "▶ opening Play edit session"
TOKEN=$(play_token)
BASE="https://androidpublisher.googleapis.com/androidpublisher/v3/applications/$PACKAGE_NAME"

EDIT=$(curl -sS -X POST -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" "$BASE/edits" -d '{}')
EDIT_ID=$(echo "$EDIT" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('id',''))")
if [[ -z "$EDIT_ID" ]]; then
  echo "✗ edit open failed:" >&2
  echo "$EDIT" >&2
  exit 4
fi
echo "  edit id: $EDIT_ID"

# ─── 3. Upload the .aab ───────────────────────────────────────────────────
echo "▶ uploading .aab (this takes ~30s for 13 MB on a fast link)"
UPLOAD=$(curl -sS -X POST \
  -H "Authorization: Bearer $TOKEN" \
  -H "Content-Type: application/octet-stream" \
  --data-binary "@$AAB" \
  "https://androidpublisher.googleapis.com/upload/androidpublisher/v3/applications/$PACKAGE_NAME/edits/$EDIT_ID/bundles?uploadType=media")
UPLOAD_VERSION=$(echo "$UPLOAD" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('versionCode',''))")
if [[ -z "$UPLOAD_VERSION" ]]; then
  echo "✗ bundle upload failed:" >&2
  echo "$UPLOAD" >&2
  exit 4
fi
echo "  uploaded versionCode $UPLOAD_VERSION"

# ─── 4. Assign to the track ───────────────────────────────────────────────
echo "▶ assigning to track: $TRACK"
TRACK_PATCH=$(curl -sS -X PUT \
  -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" \
  "$BASE/edits/$EDIT_ID/tracks/$TRACK" \
  -d "{\"track\":\"$TRACK\",\"releases\":[{\"name\":\"$VERSION_NAME\",\"versionCodes\":[\"$UPLOAD_VERSION\"],\"status\":\"completed\"}]}")
echo "$TRACK_PATCH" | python3 -c "import sys,json; d=json.load(sys.stdin); print('  releases:', [r.get('name') for r in d.get('releases',[])])"

# ─── 5. Commit the edit ───────────────────────────────────────────────────
echo "▶ committing edit"
COMMIT=$(curl -sS -X POST -H "Authorization: Bearer $TOKEN" "$BASE/edits/$EDIT_ID:commit")
COMMITTED=$(echo "$COMMIT" | python3 -c "import sys,json; d=json.load(sys.stdin); print('ok' if d.get('id') else 'FAIL')")
if [[ "$COMMITTED" != "ok" ]]; then
  echo "✗ commit failed:" >&2
  echo "$COMMIT" >&2
  exit 4
fi

echo
echo "✓ v${VERSION_NAME} (${UPLOAD_VERSION}) live on Google Play $TRACK track."
echo "  https://play.google.com/console/u/0/developers/app/$PACKAGE_NAME/tracks/$TRACK"

# ─── 6. Log to Dev Control Center ─────────────────────────────────────────
if command -v curl >/dev/null 2>&1; then
  curl -s -X POST http://sam:3333/api/apps/understudy/builds \
    -H "Content-Type: application/json" \
    -d "{\"version\":\"$VERSION_NAME\",\"build_number\":\"$UPLOAD_VERSION\",\"status\":\"playstore\",\"platform\":\"android\",\"notes\":\"Google Play $TRACK track — uploaded via ship-playstore.sh\"}" \
    >/dev/null || true
fi
